// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwE8E0RBreuYo71cviN2O8iV4W81HIH1s',
    appId: '1:128890900587:web:32eb0cdbbfabff8933e12e',
    messagingSenderId: '128890900587',
    projectId: 'putko-b4a4e',
    authDomain: 'putko-b4a4e.firebaseapp.com',
    storageBucket: 'putko-b4a4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgMs1SdReOq1fnNQg-tzfBvrWe8z8EGFQ',
    appId: '1:128890900587:android:292891d202e2162233e12e',
    messagingSenderId: '128890900587',
    projectId: 'putko-b4a4e',
    storageBucket: 'putko-b4a4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjWkKR_--VB6EYkj-f8mbgStBpnUev1I',
    appId: '1:128890900587:ios:e9aaa9371832be3133e12e',
    messagingSenderId: '128890900587',
    projectId: 'putko-b4a4e',
    storageBucket: 'putko-b4a4e.appspot.com',
    iosBundleId: 'com.hamza.putko',
  );
}
